name: Cron Test

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
