name: Date Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: test
      run: |
        day=$(date +"%u")
        echo "DOWEEK=$((day))" >> $GITHUB_ENV
           
    - name: funday
      if: env.DOWEEK == 5
      run: echo "friday = funday!"

    - name: otherday
      if: env.DOWEEK != 5
      run: echo "good, it's just a normal day"
